=== PyrokinesisStudio/Brute-Force-Game-Engine/scripts/control/Controller.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
targetNamespace="http://www.w3schools.com"
xmlns="http://www.w3schools.com"
elementFormDefault="qualified">

<xs:element name="controller" type="controllertype" />

<xs:complexType name="controllertype">
	<xs:sequence>
		<xs:element name="include" type="xs:string" minOccurs="0" maxOccurs="unbounded" />
		<xs:element name="action" maxOccurs="unbounded">
			<xs:complexType>
				<xs:sequence>
					<xs:element name="vip" type="viptype" maxOccurs="unbounded" />
				</xs:sequence>
				<xs:attribute name="id" type="xs:string" />
			</xs:complexType>
		</xs:element>
	</xs:sequence>
	<xs:attribute name="version" type="xs:integer" use="required" />
</xs:complexType>

<xs:complexType name="viptype">
	<xs:sequence>
		<xs:element name="special" type="specialtype" minOccurs="0" />
	</xs:sequence>
	<xs:attribute name="type">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="VIP_CLICK"/>
				<xs:enumeration value="VIP_STEER"/>
				<xs:enumeration value="VIP_HOLD"/>
				<xs:enumeration value="VIP_THRUST_AXIS"/>
				<xs:enumeration value="VIP_LINEAR_AXIS"/>
				<xs:enumeration value="VIP_CHEAT"/>
				<xs:enumeration value="VIP_TOGGLE"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:attribute>
	<xs:attribute name="device">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="DT_Keyboard"/>
				<xs:enumeration value="DT_Mouse"/>
				<xs:enumeration value="DT_Joystick"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:attribute>
	<xs:attribute name="axismode">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="AM_Absolute"/>
				<xs:enumeration value="AM_Relative"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:attribute>
</xs:complexType>

<xs:simpleType name="buttontype">
	<xs:restriction base="xs:string">
		<xs:pattern value="(KB|MB|JB)_[_A-Za-z0-9]+"/>
	</xs:restriction>
</xs:simpleType>

<xs:simpleType name="filtertype">
	<xs:restriction base="xs:string">
		<xs:enumeration value="BS_Pressed"/>
		<xs:enumeration value="BS_Released"/>
		<xs:enumeration value="BS_Both"/>
	</xs:restriction>
</xs:simpleType>

<xs:complexType name="specialtype">
	<xs:attribute name="axis" type="xs:integer"/>
	<xs:attribute name="button" type="buttontype"/>
	<xs:attribute name="filter" type="filtertype" />
	<xs:attribute name="flip" type="xs:boolean"/>
	<xs:attribute name="frequency" type="xs:integer"/>
	<xs:attribute name="hold" type="xs:boolean"/>
	<xs:attribute name="lower" type="buttontype"/>
	<xs:attribute name="mod" type="buttontype"/>
	<xs:attribute name="raise" type="buttontype"/>
	<xs:attribute name="range" type="xs:float"/>
	<xs:attribute name="sensitivity" type="xs:float"/>
	<xs:attribute name="sequence" type="xs:string"/>
	<xs:attribute name="step" type="xs:float"/>
	<xs:attribute name="stopatzero" type="xs:boolean"/>
	<xs:attribute name="swing" type="xs:float"/>
</xs:complexType>

</xs:schema>

=== PyrokinesisStudio/Brute-Force-Game-Engine/scripts/control/SpaceInvaders.xml
<?xml version="1.0" standalone="no" ?>

<controller
xmlns="http://www.w3schools.com"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="note Controller.xsd"
version = "1">

  <action id = "A_QUIT">
    <vip type = "VIP_CLICK">
      <special button = "KB_ESCAPE" />
    </vip>
  </action>

  <action id = "A_FPS">
    <vip type = "VIP_TOGGLE">
      <special button = "KB_F11" />
    </vip>
  </action>

  <action id = "A_SHIP_FIRE">
    <vip type = "VIP_HOLD" device = "DT_Keyboard" axismode = "AM_Absolute">
      <special frequency = "5" button = "KB_SPACE" />
    </vip>
    <vip type = "VIP_HOLD" device = "DT_Mouse">
      <special frequency = "5" button = "MB_Left" />
    </vip>
    <vip type = "VIP_HOLD" device = "DT_Joystick">
      <special frequency = "5" button = "JB_Button0" />
    </vip>
  </action>

  <action id = "A_SHIP_AXIS_Y">
    <vip type = "VIP_LINEAR_AXIS" device = "DT_Keyboard" axismode = "AM_Absolute">
      <special frequency = "100" raise = "KB_a" lower = "KB_d" step = "0.2" swing = "0.25" />
    </vip>
    <vip type = "VIP_STEER" device = "DT_Mouse" axismode = "AM_Relative">
      <special frequency = "100" axis = "0" sensitivity = "0.05" flip = "1" swing = "0.05" />
    </vip>
    <vip type = "VIP_STEER" device = "DT_Joystick" axismode = "AM_Absolute">
      <special axis = "1" sensitivity = "0.01" flip = "1" range = "32767" />
    </vip>
  </action>

</controller>

=== PyrokinesisStudio/Brute-Force-Game-Engine/scripts/control/Composer.xml
<?xml version="1.0" standalone="no" ?>

<controller
xmlns="http://www.w3schools.com"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="note Controller.xsd"
version = "1">

  <include>MyGUI.xml</include>

  <action id = "A_QUIT">
    <vip type = "VIP_CLICK">
      <special button = "KB_ESCAPE" />
    </vip>
  </action>

  <action id = "A_LOADING_MESH">
    <vip type = "VIP_CLICK">
      <special button = "KB_F1" />
    </vip>
  </action>

  <action id = "A_LOADING_MATERIAL">
    <vip type = "VIP_CLICK">
      <special button = "KB_F2" />
    </vip>
  </action>

  <action id = "A_LOADING_SKY">
    <vip type = "VIP_CLICK">
      <special button = "KB_F3" />
    </vip>
  </action>

  <action id = "A_CAMERA_AXIS_X">
    <vip type = "VIP_LINEAR_AXIS" axismode = "AM_Relative">
      <special frequency = "100" raise = "KB_KP8" lower = "KB_KP2" step = "1" />
    </vip>
  </action>

  <action id = "A_CAMERA_MOUSE_X">
    <vip type = "VIP_STEER" device = "DT_Mouse" axismode = "AM_Relative">
      <special axis = "1" sensitivity = "0.05" flip = "0" />
    </vip>
  </action>

  <action id = "A_CAMERA_AXIS_Y">
    <vip type = "VIP_LINEAR_AXIS" axismode = "AM_Relative">
      <special frequency = "100" raise = "KB_KP6" lower = "KB_KP4" step = "1" />
    </vip>
  </action>

  <action id = "A_CAMERA_MOUSE_Y">
    <vip type = "VIP_STEER" device = "DT_Mouse" axismode = "AM_Relative">
      <special axis = "0" sensitivity = "0.05" flip = "0" />
    </vip>
  </action>

  <action id = "A_CAMERA_AXIS_Z">
    <vip type = "VIP_LINEAR_AXIS" axismode = "AM_Relative">
      <special frequency = "100" raise = "KB_KP9" lower = "KB_KP7" step = "1" />
    </vip>
  </action>

  <action id = "A_CAMERA_MOUSE_Z">
    <vip type = "VIP_STEER" device = "DT_Mouse" axismode = "AM_Relative">
      <special axis = "0" sensitivity = "0.05" flip = "0" />
    </vip>
  </action>

  <action id = "A_CAMERA_MOVE">
    <vip type = "VIP_LINEAR_AXIS" axismode = "AM_Relative">
      <special frequency = "100" raise = "KB_KP_MINUS" lower = "KB_KP_PLUS" step = "0.25" />
    </vip>
  </action>

  <action id = "A_CAMERA_MOUSE_MOVE">
    <vip type = "VIP_STEER" device = "DT_Mouse" axismode = "AM_Relative">
      <special axis = "2" sensitivity = "10.0" flip = "1" />
    </vip>
  </action>

  <action id = "A_CAMERA_RESET">
    <vip type = "VIP_CLICK">
      <special button = "KB_KP_ENTER" />
    </vip>
  </action>

  <action id = "A_CAMERA_ORBIT">
    <vip type = "VIP_TOGGLE">
      <special button = "KB_KP_MULTIPLY" />
    </vip>
  </action>

  <action id = "A_SCREENSHOT">
    <vip type = "VIP_CLICK">
      <special button = "KB_F12" />
    </vip>
  </action>

  <action id = "A_CREATE_LIGHT">
    <vip type = "VIP_CLICK">
      <special button = "KB_F4" />
    </vip>
  </action>

  <action id = "A_DESTROY_LIGHT">
    <vip type = "VIP_CLICK">
      <special button = "KB_DELETE" />
    </vip>
  </action>

  <action id = "A_PREV_LIGHT">
    <vip type = "VIP_CLICK">
      <special button = "KB_PAGEUP" />
    </vip>
  </action>

  <action id = "A_NEXT_LIGHT">
    <vip type = "VIP_CLICK">
      <special button = "KB_PAGEDOWN" />
    </vip>
  </action>

  <action id = "A_FIRST_LIGHT">
    <vip type = "VIP_CLICK">
      <special button = "KB_HOME" />
    </vip>
  </action>

  <action id = "A_LAST_LIGHT">
    <vip type = "VIP_CLICK">
      <special button = "KB_END" />
    </vip>
  </action>

  <action id = "A_INFO_WINDOW">
    <vip type = "VIP_CLICK">
      <special button = "KB_i" />
    </vip>
  </action>

  <action id = "A_SUB_MESH">
    <vip type = "VIP_CLICK">
      <special button = "KB_F5" />
    </vip>
  </action>

  <action id = "A_TEX_UNIT">
    <vip type = "VIP_CLICK">
      <special button = "KB_F6" />
    </vip>
  </action>

  <action id = "A_ANIMATION">
    <vip type = "VIP_CLICK">
      <special button = "KB_F7" />
    </vip>
  </action>

  <action id = "A_ADAPTER">
    <vip type = "VIP_CLICK">
      <special button = "KB_F8" />
    </vip>
  </action>
  
</controller>

=== PyrokinesisStudio/Brute-Force-Game-Engine/scripts/control/SynchronizationTest.xml
<?xml version="1.0" standalone="no" ?>

<controller
xmlns="http://www.w3schools.com"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="Controller Controller.xsd"
version = "1">

  <include>MyGUI.xml</include>

  <action id = "A_EXIT">
    <vip type = "VIP_CLICK">
      <special button = "KB_ESCAPE" />
    </vip>
  </action>
  
  <action id = "SIMULATION_1">
    <vip type = "VIP_CLICK">
      <special button = "KB_SPACE" />
    </vip>
  </action>
  
</controller>
